apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: master-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: master-node
    spec:
      containers:
      - name: master-node
        image: gcr.io/misows-pi/master-node
        ports:
        - containerPort: 8080